import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Configuração da fonte principal sans-serif do projeto.
 * O Next injeta a fonte e expõe a variável CSS para uso global.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Configuração da fonte mono, útil para trechos técnicos,
 * códigos, identificadores ou futuras áreas administrativas.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadados globais da aplicação.
 *
 * Observação:
 * Esses valores ainda são os padrões iniciais do create-next-app.
 * Em produção, o ideal é trocar para o nome real do sistema.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Layout raiz da aplicação.
 *
 * Responsabilidades:
 * - definir a linguagem principal do HTML
 * - aplicar variáveis das fontes globais
 * - importar estilos globais
 * - renderizar todas as páginas dentro do body
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}